### ISSUE TITLE
TI ChipCon alternative to LoRa 

### ISSUE THREAD

**Issue by mrcodetastic** [SensorsIot/LoRa#2]
Hi Andreas,

Great work with your YouTube channel. Whilst this isn't actually an issue, I would like to inform you that I recently completed writing an Arduino Library for the ChipCon / Texas Instrument CC1101 low-power, long-range modules which have been around for over a decade or so as an alternative to these Hope RF / Semtech / LoRa modules. Apparently the CC chips are technically better as they use GFSK (such as used in Bluetooth) over the LoRa which is Chirp Spread Spectrum. These modules can be bought for a few bucks at most.

https://github.com/mrfaptastic/Easy-ESP-IoT-Arduino-CC1101-LORA/

It would be interesting for you to test this theory however.

**Comment by SensorsIot** [comment]
Thank you for your link. Mabe, I will try it once...
